
import React from 'react';

function Footer() {
    return (
        <footer className="mt-8 text-center text-gray-500 text-sm no-print">
            Generated by Adnan's Invoice Generator
        </footer>
    );
}
export default Footer;